# Generated by Django 5.2.15 on 2026-06-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bale_sender", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagebatch",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="messagebatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار"),
                    ("running", "در حال پردازش"),
                    ("finished", "پایان\u200cیافته"),
                    ("failed", "ناموفق"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
